### ISSUE TITLE
Support windows Os

### ISSUE THREAD

**Issue by sathanu** [webview-cs/webview-cs#1]
Is this support windows 7, 8 and 10 ?

**Comment by iwillspeak** [comment]
Not out of the box right now. But it is something I plan to add. Hopefully this weekend if I get the chance.

The .NET Code should be cross platform, it's just the DLL that's missing. You just need to get a build of my fork of webview into the right place for P/Invoke to call it.

If you're feeling adventurous you _should_ be able to get something working on windows with a few manual steps:

 1. clone this repo and build `thirdparty/webview/` with cmake. You'll need to set `BUILD_SHARED_LIBS`. `$ cmake -DBUILD_SHARED_LIBS=ON` should generate the files for you.
 2. Install the nuget package, either by building it from this repo with `$ dotnet pack` or just use the version from NuGet.
 3. Add the dll from step 1 to your output directory. Add something like the following to your csproj:
  ```csproj
    <Content Include="../../thirdparty/webview/build/webview.dll">
      <Link>webview.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
```

 4. Build
 5. Profit??

This isn't tested, but I have every confidence in it 💯

**Comment by iwillspeak** [comment]
SITREP: nope. This doesn’t _quite_ work. The windows build doesn’t export any of the symbols properly (read not at all). As I say, hopefully I will get a chance to tackle this at the weekend.

**Comment by zenakuten** [comment]
I have this fixed.  Also linux support. Pull request is pending :)

**Comment by iwillspeak** [comment]
Thanks for the PR. Have been distracted from this due to recovery from surgery. Hopefully I can get a set of multi-platform packages together soon.

**Comment by zenakuten** [comment]
I have a package with all the binaries if you want it.  Please email me and I will send them to you.

**Comment by iwillspeak** [comment]
Closing this and creating issues for sorting out the individual builds for supported platforms.
