### ISSUE TITLE
Update window icon on Windows

### ISSUE THREAD

**Issue by Namaneo** [webview-cs/webview-cs#17]
As far as I know, this is currently no possibility to change the default icon on a .NET Core console app.

However, on the documentation of zserge/webview, this seems to be possible through a resource file. I believe this could work as well on this wrapper then.

This would be nice to add support to this, or to just give some more information if this is already available.

**Comment by iwillspeak** [comment]
This is a .NET Standard library so you can still use it from a .NET Framework app and set the icon in the project properties as normal. Not sure how you accive the same thing in .NET Core.
