### ISSUE TITLE
Add bindings for native dialogs

### ISSUE THREAD

**Issue by PikminGuts92** [webview-cs/webview-cs#23]
Is there a major reason preventing this from being implemented? If not then I'd be more than happy to take a stab at it.

https://github.com/webview-cs/webview-cs/blob/946fbf553edd4ece82ab2895b9775cea949d9fe4/src/Webview/Ffi.cs#L69-L72

**Comment by iwillspeak** [comment]
No reason. I guess I just never needed it. Feel free to have a go. I’d be happy to accept a PR for it.
