### ISSUE TITLE
Readme demo Resizeable method call spelled wrong

### ISSUE THREAD

**Issue by JesseRacine** [webview-cs/webview-cs#28]
On the readme, the WebviewBuilder demo code spells the method "Resizeable" wrong, and the code doesn't run as a result. The method is spelled with two "e"'s in Resizeable, but the demo code shown in the Readme only has one "e": 
`
using Webview;
using System.Drawing;

new WebviewBuilder(new Uri("http://google.com"))
    .WithSize(new Size(1024, 768))
    **.Resizable()**
    .Debug()
    .WithInvokeCallback((webview, action) => {
      Console.WriteLine("Action: {0}", action);
    })
    .Build()
    .Run();
`

**Comment by iwillspeak** [comment]
Thanks for the report. It is a well known fact I can barely spell or type. I’d be happy to accept a PR to fix this.

**Comment by KonH** [comment]
@iwillspeak Hello! Can you please review it?

**Comment by iwillspeak** [comment]
Once again my legendary typing skills makes for great Hacktoberfest fodder.
