### ISSUE TITLE
can you help me

### ISSUE THREAD

**Issue by TheForgetTime** [webview-cs/webview-cs#31]
I'm trying to build a library similar to yours recently, except for the following function.
Unfortunately I don't know how to map this function to C#

WEBVIEW_API void webview_dispatch(webview_t w, void (*fn)(webview_t w, void *arg), void *arg);

ENV:
dotnet core 3.1
https://github.com/webview/webview : master branch
OS : Linux (ubuntu 20.04,and 18.04)

**Comment by TheForgetTime** [comment]
https://github.com/TheForgetTime/Webview-cs.git

**Comment by iwillspeak** [comment]
You will probably want to define a delegate type for the callback function. You can use `IntPtr` in place of `void*`. You'll also want to make sure you set the calling convention on both the P/Invoke declaration for `webview_dispatch` and the callback function.

Check out how the callback is handled in [`webview_alloc`](https://github.com/webview-cs/webview-cs/blob/main/src/Webview/Ffi.cs#L27::36).

**Comment by TheForgetTime** [comment]
Thank you very much for your reply.
this problem has been solved.
I looked at the c source code of this function and found that it passed the first parameter and the third parameter to the second parameter, so I already have those parameters and I don’t need to pass them.
